title: Adventures in NLP
tagline: "From Neural Networks to CF Parsers Fun in Language & Speech"
description: "From Neural Networks to CFG Parsers Fun in Language & Speech"
baseurl: ""
url: "https://DuyguA.github.io/"
email: duygu.altinok12@gmail.com
github_username:  DuyguA
linkedin_link: https://www.linkedin.com/in/duygu-altinok-4021389a/
timezone: America/New_York

markdown: kramdown
permalink: pretty
#excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM

#lsi: true

paginate: 10
paginate_path: "blog/p:num"
